GrapeSwaggerRails.options.url      = 'swagger_doc'
GrapeSwaggerRails.options.app_name = 'Grape Template API'
GrapeSwaggerRails.options.app_url  = '/'
GrapeSwaggerRails.options.api_auth = 'basic' # or 'bearer' or 'none'
GrapeSwaggerRails.options.api_key_name = 'Authorization'
GrapeSwaggerRails.options.api_key_type = 'header'